### ISSUE TITLE
v1.5 Crash sometimes with System.Net.WebException

### ISSUE THREAD

**Issue by pennz** [jwallet/spy-spotify#216]
**What is the bug ?**
Just recording, the Spytify crashs about 15~30minues, with default settings.

**How to reproduce it or what's the expected behavior ?**
1. Open Spytify
2. start recording
3. wait 15-30 minutes

With Visual Studio, when the issue happen,  I use VS 2017 to debug and found this message:
```
System.Net.WebException
  HResult=0x80131509
  Message=Unable to connect to the remote server
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.MediaTags.MP3Tags.<GetAlbumCover>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Models.Track.<GetArtExtraLargeAsync>d__92.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.MediaTags.MP3Tags.<SaveMediaTags>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Recorder.<UpdateOutputFileBasedOnMediaFormat>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Recorder.<WaveIn_RecordingStopped>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Inner Exception 1:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 74.86.142.55:443
```
And  74.86.142.55 cannot be pinged in my PC. It might have been blocked or DNS poisoned in my environment.

**Comment by pennz** [comment]
And one more thing, I often spot this problem when ADs is played. It might be unrelated, because when ADs is on, I will check Spitify.

**Comment by jwallet** [comment]
yes a release should come up soon, this is related to last.fm api not able to find any album cover
related to #178
