### ISSUE TITLE
#Error Report

### ISSUE THREAD

**Issue by vipermetcaff** [jwallet/spy-spotify#250]
#Error Report

**Application**: Spytify  
**Version**:     1.7.0.0  
**Region**:        
**Date**: 6/15/2020  
**Time**: 10:30 PM  

**Error Message**: The process cannot access the file because it is being used by another process.
 
##Stack Traces
```text
Top-level Exception
Type:    System.IO.IOException
Message: The process cannot access the file because it is being used by another process.
Source:  mscorlib
Stack Trace: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)
   at EspionSpotify.FileManager.RenameFile(String source, String destination)
   at EspionSpotify.Recorder.&lt;WaveIn_RecordingStopped&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.7.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.0.0.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - taglib-sharp, Version=2.1.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -360
--FreePhysicalMemory = 10947488
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19041

Machine
-VIPERSPC
--Manufacturer = System manufacturer
--Model = System Product Name
--TotalPhysicalMemory = 17116495872


```

**Comment by vipermetcaff** [comment]
i think i got it figured out has to do with clam win centennial

**Comment by jwallet** [comment]
spotify api issue found related to this issue
