### ISSUE TITLE
Exception from HRESULT: 0x88890008

### ISSUE THREAD

**Issue by iriefusi** [jwallet/spy-spotify#277]
Hello,
i was using V1.4 successfully but now with V 1.7 and 1.4 i have Errors.
to send the failure by email was not working so i put the log files here.

Steps:
Start spotify v. 1.1.48.625.g1c87c7f7 (Microsoft Store version) on win 10
start spytify 
klick start
> Exception Operation Failed Exception from HRESULT: 0x88890008
[spytify exception detailsd.txt](https://github.com/jwallet/spy-spotify/files/5709223/spytify.exception.detailsd.txt)

Log export pasted:
# Error Report

**Application**: Spytify  
**Version**:     1.7.0.0  
**Region**:        
**Date**: 17/12/2020  
**Time**: 10:41 AM  

**Error Message**: Exception from HRESULT: 0x88890008
 
## Stack Traces
```text
Top-level Exception
Type:    System.Runtime.InteropServices.COMException
Message: Exception from HRESULT: 0x88890008
Source:  mscorlib
Stack Trace: at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.AudioSessionManager.RefreshSessions()
   at NAudio.CoreAudioApi.MMDevice.GetAudioSessionManager()
   at EspionSpotify.AudioSessions.MainAudioSession.&lt;&gt;c.&lt;IsSpotifyPlayingOutsideDefaultAudioEndPoint&gt;b__31_0(MMDevice x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EspionSpotify.AudioSessions.MainAudioSession.&lt;IsSpotifyPlayingOutsideDefaultAudioEndPoint&gt;d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.AudioSessions.MainAudioSession.&lt;WaitSpotifyAudioSessionToStart&gt;d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Watcher.&lt;SetSpotifyAudioSessionAndWaitToStart&gt;d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Watcher.&lt;Run&gt;d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
```
 
## Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.7.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.0.0.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - taglib-sharp, Version=2.1.0.0  

## System Info  
```test
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 60
--FreePhysicalMemory = 5628008
--OSArchitecture = 64-bit
--OSLanguage = 1031
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.18363

Machine
-LAPTOP-LCMTT4AD
--Manufacturer = LENOVO
--Model = 20NT001KGE
--TotalPhysicalMemory = 16891367424


```

Tests:
I try differend Versions 1.4 to 1.7 (1.4/1.5 shut down with no exception) 
Updated my Windows
Newest spotfiy app version

**Comment by jwallet** [comment]
it looks related to the selected audio device. make sure you selected a proper audio device in settings and spotify uses the same. go to windows sounds > device and apps volume mixer

**Comment by jwallet** [comment]
do you still have the issue on 1.8?
1.8 uses a fallback if the sample rate is over maximal mp3 rate and also has a fallback to go back to stereo for anything above 2 channels
