### ISSUE TITLE
Element not found. (Exception from HRESULT: 0x80070490)

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#290]
# Exception Report

**Application**: Spytify  
**Version**:     1.8.0.0  
**Region**:        
**Date**: 12/27/2020  
**Time**: 7:45 AM  

**Error Message**: Element not found. (Exception from HRESULT: 0x80070490)
 
## Stack Traces
```text
Top-level Exception
Type:    System.Runtime.InteropServices.COMException
Message: Element not found. (Exception from HRESULT: 0x80070490)
Source:  mscorlib
Stack Trace: at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at EspionSpotify.AudioSessions.AudioMMDevicesManager..ctor(MMDeviceEnumerator audioMMDevices, String audioEndpointDeviceID)
   at EspionSpotify.AudioSessions.MainAudioSession..ctor(String audioEndPointDeviceID, IProcessManager processManager)
   at EspionSpotify.FrmEspionSpotify..ctor()
   at EspionSpotify.Program.Main()
 
```
 
## Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.8.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

## System Info  
```test
Operating System
-Microsoft Windows Server 2016 Standard
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -480
--FreePhysicalMemory = 1161500
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.14393

Machine
-WIN-VUA6POUV5UP
--Manufacturer = LENOVO
--Model = LENOVO
--TotalPhysicalMemory = 2147065856


```

**Comment by jwallet** [comment]
might be related to that issue https://github.com/StreamWhatYouHear/SWYH/issues/10

**Comment by jwallet** [comment]
indeed it happens when all devices are disabled or more probably the user has a bluetooth audio device that did not connect yet when starting spytify
![image](https://user-images.githubusercontent.com/23088305/103177775-57ef9c00-484b-11eb-8867-68523744c233.png)
