### ISSUE TITLE
The parameter 'sectionGroupName' is invalid.

### ISSUE THREAD

**Issue by jwallet** [jwallet/spy-spotify#296]
# Exception Report

**Application**: Spytify  
**Version**:     1.8.0.0  
**Region**:        
**Date**: 2020-12-28  
**Time**: 8:04 AM  

**Error Message**: The parameter 'sectionGroupName' is invalid.
Parameter name: sectionGroupName
 
## Stack Traces
```text
Top-level Exception
Type:    System.ArgumentException
Message: The parameter 'sectionGroupName' is invalid.
Parameter name: sectionGroupName
Source:  System.Windows.Forms
Stack Trace: at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at EspionSpotify.Extensions.ControlExtensions.SetPropertyThreadSafe[TControl](TControl control, MethodInvoker setter)
   at EspionSpotify.Watcher.&lt;Run&gt;d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
```
 
## Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.8.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

## System Info  
```test
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 180
--FreePhysicalMemory = 6515980
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19041

Machine
-DESKTOP-1NBJK8M
--Manufacturer = Dell Inc.
--Model = XPS 13 9360
--TotalPhysicalMemory = 17058152448


```

**Comment by jwallet** [comment]
will reopen if I have more context
