### ISSUE TITLE
Crash due to invalid config

### ISSUE THREAD

**Issue by supsm** [jwallet/spy-spotify#397]
**What is the bug ?**
> A clear and concise description of what the bug is.

When the config is invalid (e.g. when spytify crashes while writing to the file), spytify crashes on start. Crash log attached below

> Steps to reproduce the behavior or describe the expected behavior:

Open the config file location (for me in was in local app data)  
Edit the config file so the XML is no longer valid  
Start spytify

The issue is fixed by deleting the config file or replacing the config file with another one (e.g. from an older version). It would be better if spytify generated a new config file if the current one is not valid, or have an option of doing so. This kinda is a feature request, but it's also a bug report, I wasn't really sure what to categorize it as.

**Track used**
> Spotify track/playlist used : https://open.spotify.com/search

**Screenshots**
> If applicable, add screenshots to help explain your problem.

Crash log:

#Exception Report

**Application**: Spytify  
**Version**:     1.10.1.0  
**Region**:        
**Date**: 10/27/2021  
**Time**: 6:45 AM  

**Error Message**: Configuration system failed to initialize
 
##Stack Traces
```text
Top-level Exception
Type:    System.Configuration.ConfigurationErrorsException
Message: Configuration system failed to initialize
Source:  System.Configuration
Stack Trace: at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at EspionSpotify.Properties.Settings.get_app_console_logs()
   at EspionSpotify.Program.ReportException(Exception ex)
Inner Exception 1
Type:    System.Configuration.ConfigurationErrorsException
Message: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1. (C:\Users\supsm\AppData\Local\Spytify\Spytify.exe_Url_0uetdcm2l4ovaie22hjynmewaie2n5vi\1.10.1.0\user.config line 14)
Source:  System.Configuration
Stack Trace: at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
Inner Exception 2
Type:    System.Xml.XmlException
Message: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1.
Source:  System.Xml
Stack Trace: at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32&amp; startPos, Int32&amp; endPos, Int32&amp; outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.10.0.0  
 - NAudio.Lame, Version=1.1.6.0  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.10.1.0  
 - System, Version=4.0.0.0  
 - System.Configuration, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=13.0.0.0  
 - System.Net.Http, Version=4.2.0.0  
 - System.ValueTuple, Version=4.0.2.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - TagLibSharp, Version=2.2.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 11 Home Insider Preview
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -420
--FreePhysicalMemory = 18685940
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.22478

Machine
-DESKTOP-PVS0DFK
--Manufacturer = System manufacturer
--Model = System Product Name
--TotalPhysicalMemory = 34265751552


```

**Comment by jwallet** [comment]
you can go there and delete the folders until I fix it
`%USERPROFILE%\AppData\Local\Spytify\` (paste this line in Windows explorer file path)

**Comment by jwallet** [comment]
repopen if it's still the case for the latest release
